import { NoImageGeneratedError } from 'ai';
import { MockImageModelV4, MockLanguageModelV4 } from 'ai/test';
import { describe, expect, it, vi } from 'vitest';

import { DEFAULT_BRAND } from '../fixtures/brand';
import { GeminiProvider } from './gemini-provider';

const usage = {
  inputTokens: { total: 1, noCache: 1, cacheRead: 0, cacheWrite: 0 },
  outputTokens: { total: 1, text: 1, reasoning: 0 },
  totalTokens: 2,
};

const textModel = (text: string) =>
  new MockLanguageModelV4({
    doGenerate: async () => ({
      content: [{ type: 'text' as const, text }],
      finishReason: { unified: 'stop' as const, raw: undefined },
      usage,
      warnings: [],
    }),
  });

const imageModel = (bytes: Uint8Array) =>
  new MockImageModelV4({
    doGenerate: async () => ({
      images: [bytes],
      warnings: [],
      response: { timestamp: new Date(), modelId: 'mock', headers: {} },
    }),
  });

describe('GeminiProvider.generateText', () => {
  it('returns trimmed model output', async () => {
    const provider = new GeminiProvider({
      textModel: textModel('  Acme v2 is live.  '),
      imageModel: imageModel(new Uint8Array()),
      saveImage: async () => '/api/images/x.png',
      fallbackImage: async () => ({ url: 'https://fallback', alt: 'fallback' }),
    });
    await expect(
      provider.generateText({ channel: 'tweet', prompt: 'launch v2', brand: DEFAULT_BRAND, style: null }),
    ).resolves.toBe('Acme v2 is live.');
  });

  it('threads the brand into the system prompt', async () => {
    const model = textModel('out');
    const provider = new GeminiProvider({
      textModel: model,
      imageModel: imageModel(new Uint8Array()),
      saveImage: async () => '/api/images/x.png',
      fallbackImage: async () => ({ url: 'https://fallback', alt: 'fallback' }),
    });
    await provider.generateText({ channel: 'tweet', prompt: 'launch v2', brand: DEFAULT_BRAND, style: null });
    const call = model.doGenerateCalls[0]!;
    const systemMessage = call.prompt.find(message => message.role === 'system');
    expect(JSON.stringify(systemMessage)).toContain(DEFAULT_BRAND.name);
  });
});

describe('GeminiProvider.generateImage', () => {
  it('saves generated bytes and returns the local url', async () => {
    const saveImage = vi.fn().mockResolvedValue('/api/images/generated.png');
    const provider = new GeminiProvider({
      textModel: textModel('out'),
      imageModel: imageModel(new Uint8Array([1, 2, 3])),
      saveImage,
      fallbackImage: async () => ({ url: 'https://fallback', alt: 'fallback' }),
    });
    const result = await provider.generateImage({ channel: 'banner', prompt: 'launch v2', brand: DEFAULT_BRAND });
    expect(saveImage).toHaveBeenCalled();
    expect(result.url).toBe('/api/images/generated.png');
    expect(result.alt).toContain(DEFAULT_BRAND.name);
  });

  it('falls back to the placeholder when no image is generated', async () => {
    const provider = new GeminiProvider({
      textModel: textModel('out'),
      imageModel: new MockImageModelV4({
        doGenerate: async () => {
          throw new NoImageGeneratedError({ responses: [] });
        },
      }),
      saveImage: async () => '/api/images/x.png',
      fallbackImage: async () => ({ url: 'https://fallback', alt: 'fallback' }),
    });
    await expect(
      provider.generateImage({ channel: 'banner', prompt: 'launch v2', brand: DEFAULT_BRAND }),
    ).resolves.toEqual({ url: 'https://fallback', alt: 'fallback' });
  });
});
